import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { ClerkProvider } from "@clerk/nextjs";
import { DealProvider } from "@/context/DealContext";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <DealProvider>
        <html lang="en">
          <body className={poppins.className}>
            <CartProvider>
              {children}
              <Script id="admin-shortcut" strategy="afterInteractive">
                {`
                  window.addEventListener("keydown", function(e) {
                    if (e.altKey && e.code === "KeyA") {
                      e.preventDefault();
                      window.location.href = "/admin";
                    }
                  });
                `}
              </Script>
            </CartProvider>
          </body>
        </html>
      </DealProvider>
    </ClerkProvider>
  );
}
